image: node:12-alpine

stages:
  - prebuild
  - build

before_script:
  - npm

cache:
  paths:
  - ./node_modules/

prepare-images:
  image: alpine
  stage: prebuild
  before_script:
    - apk add --no-cache imagemagick
  script:
    - ./generatePNGs.sh
  artifacts:
    paths:
      - static/png

build-gatsby:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
    - public
