image: alpine

stages:
  - prepare
  - build
  - deploy

cache: {}

.nodejs:
  image: node:14
  before_script:
    - npm ci
  cache:
    key: "JS-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules
    policy: pull-push


test:
  stage: prepare
  extends: .nodejs
  script:
    - npm run test

prepare-images:
  stage: prepare
  before_script:
    - apk add --no-cache imagemagick
  script:
    - ./generatePNGs.sh
  artifacts:
    paths:
      - static/logs/png

prepare-fonts:
  stage: prepare
  image: scrlk/woff2
  script:
    - ./generateFonts.sh
  artifacts:
    paths:
      - static/fonts

build-svelte:
  stage: build
  extends: .nodejs
  script:
    - npm run export
  artifacts:
    paths:
      - __sapper__
  cache:
    policy: pull

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - cp -r __sapper__/export public
  artifacts:
    paths:
      - public
  only:
    - master
