image: alpine

stages:
  - prepare
  - build
  - deploy

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache: {}

.nodejs:
  image: node:14
  before_script:
    - npm ci
  cache:
    key: "JS-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules
      - .npm
      - cache/Cypress  
    policy: pull-push


test:
  stage: prepare
  extends: .nodejs
  image: cypress/base:14.0.0
  script:
    - npx cypress cache path
    - npx cypress cache list
    - npm run test

prepare-images:
  stage: prepare
  before_script:
    - apk add --no-cache imagemagick
  script:
    - ./generatePNGs.sh
  artifacts:
    paths:
      - static/logos/png

prepare-fonts:
  stage: prepare
  image: scrlk/woff2
  script:
    - ./generateFonts.sh
  artifacts:
    paths:
      - static/fonts

build-svelte:
  stage: build
  extends: .nodejs
  script:
    - npm run build
    - npm ci --production
  artifacts:
    paths:
      - __sapper__
      - node_modules
  cache:
    policy: pull

# pages:
#   stage: deploy
#   variables:
#     GIT_STRATEGY: none
#   script:
#     - cp -r __sapper__/export public
#   artifacts:
#     paths:
#       - public
#   only:
#     - master

include:
  - project: 'Tymek/CI'
    file: '/.dockerize.yml'
