image: alpine

stages:
  - prebuild
  - build
  - deploy

prepare-images:
  stage: prebuild
  before_script:
    - apk add --no-cache imagemagick
  script:
    - ./generatePNGs.sh
  artifacts:
    paths:
      - static/logs/png

prepare-fonts:
  stage: prebuild
  image: scrlk/woff2
  script:
    - ./generateFonts.sh
  artifacts:
    paths:
      - static/fonts

build-svelte:
  image: node:12-alpine
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - public
  cache:
    paths:
    - node_modules

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo deploy
  artifacts:
    paths:
      - public
  only:
    - master
