version: "3"

services:
  server:
    image: node:14
    container_name: tymekcz
    working_dir: /srv
    ports:
      - "5000:3000"
    volumes:
      - ./__sapper__:/srv/__sapper__
      - ./node_modules:/srv/node_modules
      - ./package.json:/srv/package.json
      - ./static:/srv/static

networks:
  wan:
    external: false
    driver: bridge
