version: "3"

services:
  server:
    image: ${IMAGE}
    container_name: ${NAME}
    build: .
    restart: always
    command: ['node', '.']
    environment:
      NODE_ENV: development
    volumes:
      - ./.env:/srv/.env
      - ./database.json:/srv/db.json
      # - ./uploads:/srv/static/uploads
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.SSLHost=www.${DOMAIN}
      - traefik.frontend.headers.SSLForceHost=true
      - com.ouroboros.enable=true
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - wan

networks:
  wan:
    external: true
